### ISSUE TITLE
Performance enhancement.

### ISSUE THREAD

**Issue by IDisposable** [ritterim/filter#20]
Any reason you don't ToList() or ToArray() the intermediate property list at https://github.com/ritterim/filter/blob/master/src/Filter/Generic/IEnumerable%601Extensions.cs#L25

**Comment by khalidabuhakmeh** [comment]
Please submit a pull request showing the difference in performance between the current implementation and the implementation you are suggesting.

And thanks for checking out the project :)

**Comment by jrusbatch** [comment]
@IDisposable It's safer this way. Since `IQueryable` implements `IEnumerable`, it's possible that calling `ToArray` here could execute an unfiltered query against the caller's database. So it's safer for us to treat the `IEnumerable` as an `IQueryable` in this situation, and leave it to the caller to materialize the collection if they choose.

**Comment by IDisposable** [comment]
Understood, perhaps we should doing the typical cast-checks optimizations that are called out in Jon Skeet's awesome blog series and eBook http://codeblog.jonskeet.uk/category/edulinq/
